package org.sd.common;

public enum Protocol{
	
	//Accoes do cliente
CLIENT_REQUEST_UPDATE,
CLIENT_REQUEST_ADD,
CLIENT_REQUEST_DEL,
CLIENT_REQUEST_ALTER,
CLIENT_REQUEST_HANDSHAKE,
	
	//Controlo do servidor

SERVER_REDIRECT,
SERVER_SERVER_REQUEST_HANDSHAKE,
SERVER_SERVER_RECIEVE_HANDSHAKE,

SERVER_SERVER_REQUEST_PROMOTION,
SERVER_SERVER_RECIEVE_PROMOTION,

SERVER_SERVER_REQUEST_TLOG,
SERVER_SERVER_RECIEVE_TLOG,

SERVER_SERVER_REQUEST_USERLIST,
SERVER_SERVER_RECIEVE_USERLIST,

SERVER_SERVER_REQUEST_SERVERLIST,
SERVER_SERVER_RECIEVE_SERVERLIST}
